development:
  adapter: postgresql
  database: kindletools_development
  hostname: localhost
  username: postgres
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kindletools_test
  hostname: localhost
  username: postgres
  password:
  pool: 5
  timeout: 5000
